// Map objects to IDs generated by Jotform
const myVet = document.getElementById("input_4");
const myOwner = document.getElementById("input_5");
const myAnimal = document.getElementById("input_17");

const paFlowUrlVets = 'https://default2ca302b2fd4a4e6a89f3ac4c6dcf2a.85.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/d46af86d45054d7dab80b0f695c0177e/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=i_QPUg80RYYFshg0tOjPED_jbrv9CAfoN5y4zk39xks';
const paFlowUrlOwners = 'https://default2ca302b2fd4a4e6a89f3ac4c6dcf2a.85.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/08a3dddda77c4862b22f98e7a6b7d538/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=97vClsSpKD8yuIhcSjfOWCpWTKmP_oSou0UWQBoRX4w';
const paFlowUrlAnimals = 'https://default2ca302b2fd4a4e6a89f3ac4c6dcf2a.85.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/84edcf11f2694dbaa19fd51c193f4cd3/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=pOMR8KdA8_5wLcSZTQ7iPHWneNwLo-XSm_fZ6_-h1go';

async function getSharePointListData(thisUrl, thisBody) {
    try {
        const response = await fetch(thisUrl, {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify(thisBody)
        });        
        if (!response.ok) {
            throw new Error(`Error: ${response.status}`);
        }
        return await response.json();
    } catch (error) {
        console.error("Failed to fetch list:", error);
    }
}

async function getVets() {
    const vetData = await getSharePointListData(paFlowUrlVets);
    vetData.forEach(vet => {
        let option = document.createElement('option');
        option.value = vet.VetID;
        option.text = vet.FullName_LF;            
        myVet.add(option);
    });
}

async function getOwners() {
    const ownerData = await getSharePointListData(paFlowUrlOwners);
    ownerData.forEach(owner => {
        let option = document.createElement('option');
        option.value = owner.OwnerID;
        option.text = owner.FullName_LF;            
        myOwner.add(option);
    });
}

async function getAnimals(element, ID) {
    myAnimal.innerHTML = "";
    myAnimal.add(new Option("Please Select", ""));
    myAnimal.add(new Option("(New Animal)", "(New Animal)"));
    const animalData = await getSharePointListData(paFlowUrlAnimals, {"element": element, "id": ID});
    animalData.forEach(animal => {
        let option = document.createElement('option');
        option.value = animal.HorseID;
        option.text = animal.HorseName; 
        option.setAttribute("data-animal", animal.Animal.Value);
        myAnimal.add(option);
    });
}



myVet.addEventListener('change', (event) => {
    getAnimals('vet', parseInt(myVet.value));
})

myOwner.addEventListener('change', (event) => {
    getAnimals('owner', parseInt(myOwner.value));
})

getVets();
getOwners();

